name: Main branch CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  standard-checks:
    name: Lint & Type
    runs-on: ubuntu-latest
    container: node:21.7.0
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Check ESLint errors
        run: npm run lint:fix
      - name: Check TypeScript errors
        run: npm run ts
